---
# Full title
title: First Generation First
# Spanish version
title-es: First Generation First
# Shorter title used for stuff like an app icon
shorttitle: FirstGenFirst
shortitle-es: FirstGenFirst
# Displayed in the header
description: Putting our first-gen students first.
description-es: Poniendo a nuestros estudiantes de primera generación en primer lugar.

youtube:
  name: First Generation First
  # URL to the channel
  url: https://www.youtube.com/c/firstgenfirst

twitter:
  name: First Gen First
  # Handle, without the "@" at the front
  handle: firstgen1st
  # URL to the account
  url: https://twitter.com/firstgen1st?s=20

instagram:
  name: First Generation First
  # Handle, without the "@" at the front
  handle: firstgenfirst
  # URL to the account
  url: https://www.instagram.com/firstgenfirst/
# Main email used for contacting
email: info@firstgenfirst.org

# The main color for the website's look (the reddish one)
themecolor: "#e3170a"
# Secondary color used for accents and stuff (the yellowish one)
secondarycolor: "#fffa89"
# Color used for footer on each webpage
footercolor: "#f2f1f0"

# Either yes or no, indicating if the header at the top of each page should stick to the top or
# scroll away with the rest of the header.
stickyheader: true


# The list of languages to offer translations for.
# Probably gonna only be Español for pretty much ever, but just in case, it's a list.
translations:
  - es


collections:
  team_members:
    output: false
    translate:
      - role
      - bio
      - content



# Other settings you probably never need to touch.
baseurl: ""
url: "https://firstgenfirst.org"
mediadir: media
host: 0.0.0.0
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - gulpfile.js
  - vendor
  - cloud_functions