---
# Full title
title: First Generation First
# Spanish version
title-es: First Generation First
# Shorter title used for stuff like an app icon
shorttitle: FirstGenFirst
shortitle-es: FirstGenFirst
# Displayed in the header
description: Putting our first-gen students first.
description-es: Poniendo a nuestros estudiantes de primera generación en primer lugar.

youtube:
  name: First Generation First
  # URL to the channel
  url: https://www.youtube.com/channel/UCmFyUfF2O_-k9U1UIYwM6RA/
  # Video ID of the video to showcase on the home page
  latestvideo: 4DZ9pOfWpW0 # Should be JUST THE ID at the end of the video's url

twitter:
  name: First Gen First
  # Handle, without the "@" at the front
  handle: firstgen1st
  # URL to the account
  url: https://twitter.com/firstgen1st?s=20

instagram:
  name: First Generation First
  # Handle, without the "@" at the front
  handle: firstgenfirst
  # URL to the account
  url: https://www.instagram.com/firstgenfirst/
# Main email used for contacting
email: info@firstgenfirst.org

# The main color for the website's look (the reddish one)
themecolor: "#e3170a"
# Secondary color used for accents and stuff (the yellowish one)
secondarycolor: "#fffa89"
# Color used for footer on each webpage
footercolor: "#f2f1f0"

# Either yes or no, indicating if the header at the top of each page should stick to the top or
# scroll away with the rest of the header.
stickyheader: true


# Controls how/which files get translated
translations:
  # A list of languages to translate to, excluding English
  langs:
    - es
  collections:   # Collections get copied to a language subdirectory with the same name as their source file.
    - name: team_members
      subdirectories:   # List of subdirectories to look at as well.
      fields:   # List of the fields that should be translated in the front matter.
        - role
        - bio
      content: true   # Whether to translate the content or not.
  pages:   # Pages get copied to their language directory with the same name as their source file.
    - lang-ref: aboutus                  # The ID of this page; the corresponding CSS file with this ID will be used.
      src: aboutus/index.html            # The source file to translate (should be in English)
      es:                                # The langauge code to translate to (and the folder the file gets outputted to)
        title: Sobre Nosotros            # The title of the new page (what gets displayed in the <title>)
        permalink: /sobrenosotros        # Where the new file should be stored in relation to the website
    - lang-ref: collegereadiness
      src: students/collegereadiness.html
      es:
        title: Preparaci&oacute;n
        permalink: /estudiantes/preparacion
    - lang-ref: applyingtocollege
      src: students/applyingtocollege/index.html
      es:
        title: Aplicando a la Universidad
        permalink: /estudiantes/aplicandoalauniversidad
    - lang-ref: donate
      src: more/donate.html
      es:
        title: Donar
        permalink: /donar.html
    - lang-ref: faq
      src: students/scholarship/faq.html
      es:
        title: Preguntas Más Frecuentes
        permalink: /estudiantes/beca/pmf
    - lang-ref: home
      src: home.html
      es:
        title: Hogar
        permalink: /hogar
    - lang-ref: ourteam
      src: aboutus/ourteam.html
      es:
        title: Nuestro Equipo
        permalink: sobrenosotros/nuestroequipo
    - lang-ref: parentsandteachers
      src: more/parentsandteachers.html
      es:
        title: Padres &amp; Maestros
        permalink: /padresymaestros
    - lang-ref: scholarship
      src: students/scholarship/index.html
      es:
        title: Beca de FGF
        permalink: /estudiantes/beca
    - lang-ref: students
      src: students/index.html
      es:
        title: Estudiantes
        permalink: /estudiantes


collections:
  team_members:
    output: false


# Other settings you probably never need to touch.
baseurl: ""
url: "https://firstgenfirst.org"
mediadir: media
host: 0.0.0.0
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - gulpfile.js
  - vendor
  - translate_files.js